"""Core enums and type aliases for the backtesting engine.

All enums are defined here to avoid circular imports. Modules import
from this file and never define their own enums.
"""

from enum import Enum, auto


class TokenSide(Enum):
    """Which token in the binary market."""
    YES = "YES"
    NO = "NO"


class EventKind(Enum):
    """Types of events in the unified timeline.

    Integer values define processing priority at the same timestamp:
    lower value = processed first. This ensures market data is ingested
    before the engine acts on it.
    """
    UNDERLYING_PRICE = 0
    OPTIONS_CHAIN = 1
    BOOK_SNAPSHOT = 2
    TRADE = 3
    MARKET_OPEN = 4
    MARKET_CLOSE = 5
    RESOLUTION = 6
    # Internal events (generated by the engine, not data)
    ORDER_VISIBLE = 100
    CANCEL_EFFECTIVE = 101


class Side(Enum):
    """Order side."""
    BUY = "BUY"
    SELL = "SELL"


class OrderStatus(Enum):
    """Order lifecycle states.

    State machine:
      PENDING_SUBMIT -> ACTIVE -> FILLED
                               -> PARTIALLY_FILLED -> FILLED
                               -> PENDING_CANCEL -> CANCELLED
                                                  -> FILLED (race condition)
      PENDING_SUBMIT -> REJECTED
    """
    PENDING_SUBMIT = auto()
    ACTIVE = auto()
    PARTIALLY_FILLED = auto()
    PENDING_CANCEL = auto()
    FILLED = auto()
    CANCELLED = auto()
    REJECTED = auto()


class QueueMode(Enum):
    """Queue position assignment model."""
    CONSERVATIVE = auto()    # Back of queue (all depth ahead)
    PROBABILISTIC = auto()   # Random position in queue
    OPTIMISTIC = auto()      # Front of queue (nothing ahead)


class FillMode(Enum):
    """Which fill engine to use."""
    TRADE_DRIVEN = auto()    # Production: only trades trigger fills
    SNAPSHOT_ONLY = auto()   # Fallback: BBO movement triggers fills


class PositionMode(Enum):
    """How collateral is handled for short positions."""
    COLLATERAL_BACKED = auto()   # Lock $1 collateral per short share
    INVENTORY_BACKED = auto()    # Must hold opposing token to sell
