"""Priority queue for internal engine events (ORDER_VISIBLE, CANCEL_EFFECTIVE).

These events are generated by the engine and injected into the timeline
at future timestamps. Uses bisect for sorted insertion.
"""

from bisect import insort
from dataclasses import dataclass

from bt_engine.types import EventKind


@dataclass(frozen=True, slots=True)
class InternalEvent:
    """An engine-generated event scheduled for a future timestamp."""
    timestamp_us: int
    kind: EventKind          # ORDER_VISIBLE or CANCEL_EFFECTIVE
    order_id: str
    sequence: int            # For deterministic ordering

    def __lt__(self, other: "InternalEvent") -> bool:
        if self.timestamp_us != other.timestamp_us:
            return self.timestamp_us < other.timestamp_us
        if self.kind.value != other.kind.value:
            return self.kind.value < other.kind.value
        return self.sequence < other.sequence


class InternalEventQueue:
    """Sorted queue of future internal events."""

    def __init__(self):
        self._events: list[InternalEvent] = []
        self._sequence = 0

    def schedule(self, timestamp_us: int, kind: EventKind, order_id: str) -> None:
        seq = self._sequence
        self._sequence += 1
        event = InternalEvent(
            timestamp_us=timestamp_us,
            kind=kind,
            order_id=order_id,
            sequence=seq,
        )
        insort(self._events, event)

    def peek_timestamp(self) -> int | None:
        """Return the timestamp of the next event, or None if empty."""
        if self._events:
            return self._events[0].timestamp_us
        return None

    def pop_events_at(self, timestamp_us: int) -> list[InternalEvent]:
        """Pop all events at exactly this timestamp."""
        result = []
        while self._events and self._events[0].timestamp_us == timestamp_us:
            result.append(self._events.pop(0))
        return result

    def pop_events_up_to(self, timestamp_us: int) -> list[InternalEvent]:
        """Pop all events with timestamp <= the given time."""
        result = []
        while self._events and self._events[0].timestamp_us <= timestamp_us:
            result.append(self._events.pop(0))
        return result

    def __len__(self) -> int:
        return len(self._events)

    @property
    def empty(self) -> bool:
        return len(self._events) == 0
